products = [
    {
        "id": 1,
        "name": "Mussarela",
        "ingredients": ["Molho", "Mussarela", "Azeitona", "Orégano"],
        "price": 49.90,
        "category": "Tradicional",
        "is_popular": True,
        "available": True,
    },
    {
        "id": 2,
        "name": "Marguerita",
        "ingredients": ["Molho", "Mussarela", "Tomate", "Manjericão", "Orégano"],
        "price": 54.90,
        "category": "Tradicional",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 3,
        "name": "Alho Frito",
        "ingredients": ["Molho", "Mussarela", "Alho Frito na Manteiga"],
        "price": 52.90,
        "category": "Tradicional",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 4,
        "name": "Alho Poró",
        "ingredients": ["Molho", "Mussarela", "Alho Poró"],
        "price": 55.90,
        "category": "Tradicional",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 5,
        "name": "Calabresa",
        "ingredients": ["Molho", "Mussarela", "Calabresa", "Orégano"],
        "price": 53.90,
        "category": "Tradicional",
        "is_popular": True,
        "available": True,
    },
    {
        "id": 6,
        "name": "Presunto",
        "ingredients": ["Molho", "Mussarela", "Presunto", "Azeitona"],
        "price": 54.90,
        "category": "Tradicional",
        "is_popular": True,
        "available": True,
    },
    {
        "id": 7,
        "name": "Toscana",
        "ingredients": ["Molho", "Mussarela", "Calabresa Moída", "Cebola", "Tomate"],
        "price": 56.90,
        "category": "Tradicional",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 8,
        "name": "Bacon Crocante",
        "ingredients": ["Molho", "Mussarela", "Bacon"],
        "price": 59.90,
        "category": "Especial",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 9,
        "name": "Bacon e Milho",
        "ingredients": ["Molho", "Mussarela", "Bacon", "Milho"],
        "price": 58.90,
        "category": "Especial",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 10,
        "name": "Palmito",
        "ingredients": ["Molho", "Mussarela", "Palmito"],
        "price": 59.90,
        "category": "Especial",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 11,
        "name": "Quatro Queijos",
        "ingredients": ["Molho", "Mussarela", "Provolone", "Catupiry", "Parmesão"],
        "price": 64.90,
        "category": "Especial",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 12,
        "name": "À Moda",
        "ingredients": [
            "Molho",
            "Mussarela",
            "Calabresa",
            "Tomate",
            "Catupiry",
            "Milho",
        ],
        "price": 62.90,
        "category": "Especial",
        "is_popular": True,
        "available": True,
    },
    {
        "id": 13,
        "name": "Frango com Catupiry",
        "ingredients": ["Molho", "Mussarela", "Frango", "Catupiry"],
        "price": 61.90,
        "category": "Especial",
        "is_popular": True,
        "available": True,
    },
    {
        "id": 14,
        "name": "Atum",
        "ingredients": ["Molho", "Mussarela", "Atum", "Cebola"],
        "price": 63.90,
        "category": "Especial",
        "is_popular": False,
        "available": True,
    },
    {
        "id": 15,
        "name": "Portuguesa",
        "ingredients": [
            "Molho",
            "Mussarela",
            "Presunto",
            "Calabresa",
            "Pimentão",
            "Cebola",
            "Azeitona",
        ],
        "price": 62.90,
        "category": "Especial",
        "is_popular": True,
        "available": True,
    },
]
